[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/auth/*"
  status = 200
  to = "/.netlify/functions/api/:splat"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false